[package]
name = "aoc"
version = "0.1.0"
authors = ["Joel Martinsson <Joel.Martinsson@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_reader = {path="../aoc_reader"}
